### ISSUE TITLE
provide a .env.sample and update readme

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#1]
- add a .env.sample file with the content
```
REACT_APP_STEPZEN_API_KEY={{STEPZEN_API_KEY}}
REACT_APP_STEPZEN_ENDPOINT={{STEPZEN_ENDPOINT}}
```

- and update the readme to reflect that you can `cp .env.sample .env` to get started filling in your environment variables.

**Comment by Aayush0606** [comment]
Hey can I contribute to this ?

**Comment by KKVANONYMOUS** [comment]
Hi @Cerchie I would like to work on this issue

**Comment by Cerchie** [comment]
@Aayush0606 yes you can! I advise that you consult our SUPPORT, CONTRIBUTING_FOR_HACKTOBERFEST, and CODE_OF_CONDUCT documents prior to contributing. 

@KKVANONYMOUS I'll take a first-come, first-serve approach and give this to Aayush. Feel free to take a look at our other unassigned issues.
