### ISSUE TITLE
document scalars in api_spacex_land.graphql

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#11]
There are a few custom [scalar types](https://graphql.org/learn/schema/#scalar-types) in the graphql schema that need documentation.

In GraphQL, documentation is outlined with triple quotes, like

```graphql
"""
this scalar is an RFC-3339 encoded date
"""
scalar Date
```

**Comment by aloks98** [comment]
I'd love to take up this issue. Please assign me, thanks!

**Comment by Cerchie** [comment]
You're welcome to it, @aloks98 ! Per our [contributing guidelines](https://github.com/stepzen-samples/stepzen-spacex-graphql/blob/main/CONTRIBUTING_FOR_HACKTOBERFEST.md) I'm assigning one issue at a time, so let's wait on the other one.
Thanks for contributing!
