### ISSUE TITLE
Create schema for SpaceX REST API

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#14]
We want to create a schema to integrate the SpaceX REST API into the StepZen data layer. 

You can view documentation for [connecting to REST](https://stepzen.com/docs/connecting-backends/how-to-connect-a-rest-service) and [designing your schema](https://stepzen.com/docs/design-a-graphql-schema).

As always, feel free to reach out for help! calendly.com/lucia-stepzen

This issue is a sub-issue of #13

**Comment by gagandeepp** [comment]
Is this open for work ,I can work on this

**Comment by Cerchie** [comment]
This issue is remaining available for now. :)

**Comment by gagandeepp** [comment]
assign this to me

**Comment by Cerchie** [comment]
Hey @gagandeepp, although I appreciate your interest in many of our issues, we want to make space for a variety of contributors. We've assigned you #7

**Comment by oliver-pham** [comment]
Hi @Cerchie ! I'm interested in giving this issue a try. Can you assign it to me?
