### ISSUE TITLE
Create page to fetch launches by launch year

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#15]
This issue is a sub-issue of #13 and is dependent upon the completion of #14 

Once we have our REST API schema in place, we will need to consume the data in a React page. We'll use Apollo and the USE_QUERY hook. You can see an example of this on the homepage, in src/App.js.

As always, please feel free to reach out for help. :) calendly.com/lucia-stepzen

**Comment by gagandeepp** [comment]
Can you please assign this to me?

**Comment by Cerchie** [comment]
This issue is remaining available for now. :)

**Comment by gagandeepp** [comment]
aSSIGN THIS TO ME

**Comment by Cerchie** [comment]
Hey @gagandeepp, although I appreciate your interest in many of our issues, we want to make space for a variety of contributors. We've assigned you #7
