### ISSUE TITLE
update homepage styling

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#3]
Right now the styling on the homepage is primitive:

<img width="1067" alt="Screen Shot 2021-08-31 at 1 27 22 PM 1" src="https://user-images.githubusercontent.com/54046179/131571387-21e15269-5449-46fb-ba85-ba24d2bcba54.png">

We could:

- remove bullet points
- create a card or box or something for the data pulled in to be displayed 

Let me know if you have more ideas!

**Comment by rek990** [comment]
Hi, I assume you are referring to the App.js file? I might be able to make some contributions to this one. I work with React and Chakra UI, if that is helpful.

**Comment by Cerchie** [comment]
@rek990 Go ahead, and thanks for helping out! I advise that you read the SUPPORT, CONTRIBUTING_FOR_HACKTOBERFEST, and CODE_OF_CONDUCT documents before getting started.

**Comment by rek990** [comment]
@Cerchie sounds good and thank you!

**Comment by rek990** [comment]
Hello,

Attached is a screen shot of the updates I have made thus far to the homepage. Was something like this what you had in mind? 

Best,
Rebecca

![Screenshot from 2021-10-09 21-51-37](https://user-images.githubusercontent.com/47927958/136678468-80e023d5-bc0f-4919-b7cb-e7522a676187.png)
