### ISSUE TITLE
show information on the homepage for first five launches

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#5]
Currently the homepage shows information for one capsule by its id.
Let's change it to information on the first five launches. This will mean changing the `GET_QUERY` variable in `src/App.js` to the GraphQL query that will do that.

**Comment by gagandeepp** [comment]
Interested , assign me

**Comment by Cerchie** [comment]
This issue is remaining available for now. :) see explanation of why in https://github.com/stepzen-samples/stepzen-spacex-graphql/issues/7

**Comment by gagandeepp** [comment]
> This issue is remaining available for now. :) see explanation of why in #7

Didnt get you.
if you guys are waiting for the october. I will raise my PR after 1st october.

**Comment by gagandeepp** [comment]
> > This issue is remaining available for now. :) see explanation of why in #7
> 
> Didnt get you. if you guys are waiting for the october. I will raise my PR after 1st october.

At least you guys can assign the tickets to the contributors as of now

**Comment by Cerchie** [comment]
@gagandeepp want to hop on a call to discuss? https://calendly.com/lucia-stepzen/30min
I'm available starting Oct 6
