### ISSUE TITLE
create a page that displays rocket information

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#7]
- create a page similar to the homepage that displays information on the first ten rockets returned from the request
- add a link to this page on the homepage

**Comment by gagandeepp** [comment]
Interested ,please assign

**Comment by gagandeepp** [comment]
@Cerchie  Can you share the url of home page and screenshot as well?

**Comment by Cerchie** [comment]
@gagandeepp 
I'll be answering questions once October begins. In the meantime, please see the README.

**Comment by gagandeepp** [comment]
@Cerchie  I am using this endpoint and it is only listing 4 rockets https://api.spacex.land/graphql/
Schema:
{
  rockets {
    id
    name
    wikipedia
  }
}

**Comment by gagandeepp** [comment]
Following is the result set

{
  "data": {
    "rockets": [
      {
        "id": "falcon1",
        "name": "Falcon 1",
        "wikipedia": "https://en.wikipedia.org/wiki/Falcon_1"
      },
      {
        "id": "falcon9",
        "name": "Falcon 9",
        "wikipedia": "https://en.wikipedia.org/wiki/Falcon_9"
      },
      {
        "id": "falconheavy",
        "name": "Falcon Heavy",
        "wikipedia": "https://en.wikipedia.org/wiki/Falcon_Heavy"
      },
      {
        "id": "starship",
        "name": "Starship",
        "wikipedia": "https://en.wikipedia.org/wiki/SpaceX_Starship"
      }
    ]
  }
}

**Comment by gagandeepp** [comment]
https://github.com/stepzen-samples/stepzen-spacex-graphql/pull/19
