### ISSUE TITLE
add debugging type to graphql

### ISSUE THREAD

**Issue by Cerchie** [stepzen-samples/stepzen-spacex-graphql#9]
this code adds a debugger with a call to httpbin.org to help users view what is being sent:

```graphql
type debug {
  args: JSON
  data: JSON
  files: JSON
  form: JSON
  headers: JSON
  json: JSON
  method: String
  url: String
}

type Query {
  debugger(id: String!): debug
    @rest(
      endpoint:"https://httpbin.org/anything/$id"
    )
}
```
We need it in the `api_spacex_land.graphql` file.

**Comment by rek990** [comment]
Hi, to ensure I'm not oversimplifying the issue, is this simply a matter of transferring the above code into `api_spacex_land.graphql`? If so, I might be interested in giving this one a try!

**Comment by YolandaHaynes** [comment]
Hello! I would like to give this a try.

**Comment by Cerchie** [comment]
@YolandaHaynes it's yours. Check out our CONTRIBUTING_FOR_HACKTOBERFEST, SUPPORT, and CODE_OF_CONDUCT docs before getting started. :)

**Comment by Cerchie** [comment]
Hi @codiini ! @YolandaHaynes is still working on it as far as I know, so I'm leaving it assigned to her for now.
